# Arrays

Arrays are a continuous block of memory containing multiple elements, and their size cannot be changed. In Python, arrays are actually lists, which can change in length. 

To get proper arrays, we're going to use a *library*. This is a collection of code that's already written for us, and we just have to `import` it to use it in our own code. 

In [1]:
# NumPy brings in a lot of features related to arrays. The 'as np' bit lets us refer to it as np in our code.
import numpy as np

Now to create an empty array using NumPy:

In [2]:
# This creates an array of length 10 without initialising the values
our_array = np.empty(10)
print(our_array)

[5.71426876e-312 1.77863633e-322 0.00000000e+000 0.00000000e+000
 0.00000000e+000 3.43644171e+179 3.27043848e+179 5.20286388e-090
 1.81615061e-052 4.07794782e-315]


Notice that when we print this out, we seem to get random numbers. This is because we haven't set the values to anything, so the numbers are just whatever was lying around in the block of memory.

There are also a number of functions that initialise the array for us, such as:

In [3]:
ones = np.ones(5)
print(ones)

zeros = np.zeros(5)
print(zeros)

sevens = np.full(10, 7)
print(sevens)

[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0.]
[7 7 7 7 7 7 7 7 7 7]


And we can also create 2D arrays using any of these by passing a *tuple* as the shape:

In [4]:
example = np.zeros((2, 3))
print(example)

[[0. 0. 0.]
 [0. 0. 0.]]


Don't worry about remembering any of these for your exam though. When writing pseudocode, you can just create empty arrays like normal (eg. `array new_array[10]`), but they'll be useful for the following exercises.

### Exercise 1

Write a function that creates an array of the length `length` and fills it with the numbers 0 to `length - 1`.

In [7]:
def array_fill(length):
    arr = np.empty(length)
    # Code here

    return arr

print("Success!" if array_fill(10) == np.arange(10) else f"Failed. Expected {np.arange(10)} got {array_fill(10)}")

Failed. Expected [ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ] got [5.71426876e-312 1.77863633e-322 0.00000000e+000 0.00000000e+000
 0.00000000e+000 3.43644171e+179 3.27043848e+179 5.20286388e-090
 1.81615061e-052 4.07794782e-315]


C:\Users\jake_\AppData\Local\Temp/ipykernel_11004/136642394.py:7: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print("Success!" if array_fill(10) == np.linspace(0, 10) else f"Failed. Expected {np.linspace(0, 10)} got {array_fill(10)}")
